#!/bin/bash
#SBATCH -J mse
#SBATCH --constraint=a100
#SBATCH -t 5:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --gres=gpu:1
#SBATCH --mail-user=vk9342@princeton.edu
#SBATCH --mail-type=all
#SBATCH --array=25,50,75,100,125,150,175,200,400,800,1400
#SBATCH -o /home/vk9342/USRP2024/pytorch/joboutput/mse_transfer10_network2_%a_EQ_0_BSQ.o%j

conda activate usrp

n_sims=$SLURM_ARRAY_TASK_ID
python main_copy_fixed0.py --n_sims $n_sims