#!/bin/bash
#SBATCH -J mse
#SBATCH --constraint=a100
#SBATCH -t 8:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --gres=gpu:1
#SBATCH --mail-user=vk9342@princeton.edu
#SBATCH --mail-type=all
#SBATCH -o /scratch/network/vk9342/USRP2024/pytorch/revisions/joboutput/mse_transfer10_network2_50_nwLH_22000_BSQ_MPk_combined_weights_revisions.o%j

conda activate usrp

n_sims=50
python main_copy_combined_weights_22000.py --n_sims $n_sims  
