#!/bin/bash
#SBATCH -J mse
#SBATCH --constraint=a100
#SBATCH -t 5:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --gres=gpu:1
#SBATCH --mail-user=vk9342@princeton.edu
#SBATCH --mail-type=all
#SBATCH -o /home/vk9342/USRP2024/pytorch/joboutput/mse_transfer10_network2_175_nwLH_22000_BSQ_node_test2.o%j

conda activate usrp

n_sims=175
python main_copy_fixed_ft_test_22000.py --n_sims $n_sims   #start with this when resume
